### ISSUE TITLE
YES FINALLY

### ISSUE THREAD

**Issue by ProletarianBanner** [comandanteghoul/vanguardvaluesreclaimed#1]
I've been wanting to take this again for so long, I'm a Hoxhaist now, so I have to take it again to see what I get, you dig?

**Comment by comandanteghoul** [comment]
> I've been wanting to take this again for so long, I'm a Hoxhaist now, so I have to take it again to see what I get, you dig?

Totally get you. Enjoy, and thanks for taking the quiz!
