### ISSUE TITLE
Military/Peace Axis nitpicking

### ISSUE THREAD

**Issue by ProletarianBanner** [comandanteghoul/vanguardvaluesreclaimed#2]
So, on the military or peace axis I had scored "Juche," I of course see that you are trying to keep it relatively the same to the original quiz, but of course this should be changed to Songun as Songun is the military-first policy, Juche i s the ideology, AKA the Juche idea. I am not Juche, however, I kind of used to be. I understand a good bit about the DPRK, its ideologies and politics, it is called Songun politics.

**Comment by comandanteghoul** [comment]
> So, on the military or peace axis I had scored "Juche," I of course see that you are trying to keep it relatively the same to the original quiz, but of course this should be changed to Songun as Songun is the military-first policy, Juche i s the ideology, AKA the Juche idea. I am not Juche, however, I kind of used to be. I understand a good bit about the DPRK, its ideologies and politics, it is called Songun politics.

I appreciate you pointing that out! I'll go fix that and the other misspelling in a moment. Thanks again!
